--
-- PostgreSQL database dump
--

\restrict 2OcdjgdsopxDpyhBFKycmDneCHfBATRVMTui4Mc7H0MXTHfPeb0UxhgLQkYShOH

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: footnote; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.footnote (
    "Id" integer NOT NULL,
    "Note" text NOT NULL,
    "Source" text,
    "Type" integer NOT NULL
);


--
-- Name: footnote_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.footnote ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."footnote_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260213192819_Init	10.0.3
\.


--
-- Data for Name: footnote; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.footnote ("Id", "Note", "Source", "Type") FROM stdin;
29	Breathe deeply. You are in the present moment.	\N	4
30	Bring awareness into the moment.	\N	4
139	The risk of injury increases by up to 70 percent when young athletes get less than eight hours of sleep.	https://pubmed.ncbi.nlm.nih.gov/25028798/	64
28	Be mindful of your posture throughout the day, and realign yourself regularly.	\N	4
287	On the days people drank coffee, they took an average of 1,000 extra steps per day. But they slept about 36 fewer minutes per night, on average.	https://www.health.harvard.edu/heart-health/does-coffee-help-or-harm-your-heart	16
146	Adults who stay well-hydrated appear to be healthier, develop fewer chronic conditions, such as heart and lung disease, and live longer than those who may not get sufficient fluids.	https://www.nih.gov/news-events/news-releases/good-hydration-linked-healthy-aging	16
319	Stone fruits. Cherries, peaches, apricots, and plums are all examples of stone fruits. These fruits contain fiber, vitamin C, potassium, and a variety of phytochemicals associated with their colors. For example, cherries have garnered the lion's share of the research among stone fruits. Some studies suggest that cherries can reduce pain and soreness after exercise as well as a reduced risk of gout attacks. The high levels of phenolic compounds in cherries, which have been linked to reduced inflammation, may be behind those benefits.	Harvard Medical School	16
321	Pomegranates. Those tiny pomegranate seeds contain big rewards of vitamins C and K, potassium, fiber, and potent phytochemicals such as anthocyanin and resveratrol. These nutrients may be behind the potential benefits of eating pomegranates.	Harvard Medical School	16
27	Paying attention to posture can help you look and feel better.	https://www.health.harvard.edu/pain/posture-and-back-health	4
331	All of my accomplishments matter.	\N	256
332	My best is always good enough.	\N	256
333	Each day I do the best I can.	\N	256
334	My curiosity is stronger than my fear.	\N	256
25	You are awesome!	\N	2
335	I am unaffected by the judgement of others.	\N	256
339	Be better, not bitter.	\N	256
340	I can do this.	\N	256
341	I am confident and strong.	\N	256
342	I believe in myself.	\N	256
344	I will not be put down by people or external circumstances.	\N	256
345	I accept who I am.	\N	256
346	My workout goals are attainable.	\N	256
347	I am worthy and deserve respect.	\N	256
348	I am not defined by laziness, self-doubt, or numbers.	\N	256
349	I embrace both my good and bad qualities.	\N	256
336	Reward yourself after achieving special workout related milestones. Nothing motivates like success!	\N	128
343	Reward yourself with a delicious protein shake after a completed workout!	\N	128
17	Be aware that training too hard or too often can cause overuse injuries like stress fractures, stiff or sore joints and muscles, and inflamed tendons and ligaments.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	32
59	Expose your eyes to natural light.	\N	4
56	A truly ergonomic workstation is one that you regularly push away from.	\N	4
42	Enjoy the simple things.	\N	4
72	For increased stability work, try switching out a bench or chair for an exercise ball.	\N	8
26	You body is meant to move. Shift positions, or get up to move around every hour of the day.	https://www.health.harvard.edu/heart-health/why-you-should-move-even-just-a-little-throughout-the-day	8
68	Incorporate strength into your everyday life: Squat instead of bending over; Squat up from a seated position; Take the stairs; Use a standing desk; Sit on an exercise ball; Walk with ankle weights/a weighted vest; Ride a bike to local restaurants.	\N	8
97	Vitamin D is crucial for adequate calcium absorbtion necessary to create strong, healthy bones.	https://www.health.harvard.edu/staying-healthy/essential-nutrients-your-body-needs-for-building-bone	8
20	Watch for signs of overheating, such as headache, dizziness, nausea, faintness, cramps, or palpitations.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	8
21	If you stop exercising for a while, drop back to a lower level of exercise initially.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	8
40	Breathe comfortably and continuously while stretching.	https://www.health.harvard.edu/staying-healthy/six-tips-for-safe-stretches	8
39	Stretch only to the point of mild tension, never to the point of pain.	https://www.health.harvard.edu/staying-healthy/six-tips-for-safe-stretches	32
67	Standing at a desk? Consider standing calf raises (with a weighted vest or ankle weights) to strengthen the lower legs.	\N	32
320	Citrus. Oranges, grapefruit, lemons, and limes are famously rich in vitamin C. They also contain fiber, potassium, calcium, B vitamins, copper, and anti-inflammatory phytochemicals such as flavonoids and carotenoids. Though there is little human research on citrus, the nutrients found in citrus fruits have been associated with heart-protective effects.	Harvard Medical School	16
48	Be better, not bitter.	\N	4096
89	Exercise is considered the most effective, non-drug treatment for reducing pain and improving movement in people with arthritis.	https://www.arthritis.org/health-wellness/healthy-living/physical-activity/getting-started/benefits-of-exercise-for-osteoarthritis	64
84	Look away from screens and squeeze your eyes shut periodically to maintain good eye health.	https://www.health.harvard.edu/diseases-and-conditions/electronic-screen-alert-avoid-this-vision-risk	4
66	Sitting at a desk? Consider seated calf raises (with ankle weights) to strengthen the lower legs.	\N	32
352	A dull blade is actually more dangerous to use than one that is sharp. A dull blade needs more pressure to cut, increasing the chance that the knife will slip with great force behind it. A sharp knife "bites" the surface more readily. 	https://www.urmc.rochester.edu/encyclopedia/content?contenttypeid=1&contentid=263	512
47	When life gives you lemons, stick them on your barbell. Conquer life's lemons!	\N	128
37	Never sacrifice good form by hurrying to finish reps or sets, or struggling to lift heavier weights.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	32
54	To increase strength and power, rest for 2-5 minutes between sets.	https://www.bodybuilding.com/content/how-long-should-you-rest-between-sets.html	32
53	To increase hypertrophy (muscle mass), rest for 30-90 seconds between sets.	https://www.bodybuilding.com/content/how-long-should-you-rest-between-sets.html	32
52	To increase muscular endurance, rest for 30 seconds or less between sets.	https://www.bodybuilding.com/content/how-long-should-you-rest-between-sets.html	32
45	Use music or audio books to keep you entertained while you workout.	\N	32
49	As you start out, it's best to build muscle endurance with high reps and low sets. As you progress, use higher weights with lower reps and more sets to build strength.	\N	32
140	As the years pass, muscle mass in the body generally shrinks, and strength and power decline. Sarcope­nia—defined as age-related muscle loss—can begin at around age 35 and occurs at a rate of 1-2 percent a year for the typical person. Studies suggest that strength and power training can help reverse these effects and restore muscle function.	https://www.health.harvard.edu/exercise-and-fitness/strength-and-power-training-for-older-adults#excerpt	32
38	Listen to your body. Hold off on exercise when you're feeling faint, fatigued or suffer persistent aches and pains in joints after exercising.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	32
16	Take five to 10 minutes to warm up and cool down properly.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	32
22	Plan to start slowly and boost your activity level gradually unless you are already exercising frequently and vigorously.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	32
19	For strength training, good form is essential. Initially use no weight, or very light weights, when learning the exercises.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	32
44	Don't be discouraged if you stop for a while. Everybody needs a holiday. Get started again gradually and work up to your old pace.	https://www.heart.org/en/healthy-living/fitness/getting-active/getting-started---tips-for-long-term-exercise-success	128
36	When sitting down, keep your chin parallel to the floor; your shoulders, hips, and knees at even heights; and your knees and feet pointing straight ahead.	https://www.health.harvard.edu/staying-healthy/why-good-posture-matters	4
32	Take a moment to pause and come back to the present.	\N	4
33	Are you aware? How does your body feel? 	\N	4
61	Take your time and eat some fruit. Slowly. Notice the flavor, the texture, the freshness.	\N	4
127	Enjoy the little things.	\N	4
174	All of my accomplishments matter.	\N	4096
154	Adding yoga to aerobic exercise may help lower high blood pressure.	https://www.health.harvard.edu/exercise-and-fitness/adding-yoga-to-aerobic-exercise-may-help-lower-high-blood-pressure	64
291	Enjoyment for high-intensity interval exercise increases with chronic training.	https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5156428/pdf/pone.0168534.pdf	64
153	Don't exercise immediately after eating.	https://www.health.harvard.edu/nutrition/stomach-troubles-with-no-clear-cause-heres-what-you-can-do	8
98	One of the most important contributors to muscular growth is the tension that muscle fibers experience under load. Want to buff a certain muscle? Squeeze it throughout the exercise.	https://www.ironmaster.com/blog/importance-of-muscular-tension-for-maximized-workouts/	32
85	Even mild dehydration can lead to increased post-workout fatigue and pain. Most people underestimate the amount of water they lose through sweat.	https://www.strongerbyscience.com/research-spotlight-dehydration/	32
51	Have a beautiful day!	\N	2
120	It's recommended to get at least 150 minutes of moderate-intensity or 75 minutes of vigorous exercise per week.	https://www.cdc.gov/physicalactivity/basics/adults/index.htm	8
121	Bend at the hips and knees, not at the waist.	https://www.urmc.rochester.edu/encyclopedia/content.aspx?contenttypeid=1&contentid=4456	8
1	People who'd averaged at least 12 hours a day sitting were 63% likelier to develop dementia than those who'd spent less than 10 hours daily in a chair. Furthermore, exercise didn't seem to change those odds, since among people who sat for 10 hours or more daily, those who worked out were as prone to dementia as those who exercised very little.	https://www.health.harvard.edu/mind-and-mood/long-hours-sitting-can-raise-dementia-odds-despite-exercise	16
3	By harnessing the power of vasoconstriction and vasodilation, [cold water] therapies stimulate blood flow, deliver oxygen and nutrients, and remove cellular waste more efficiently.	https://coldplungeculture.com/do-ice-baths-improve-circulation/	16
2	Spending just three hours a day outside soaking up natural light can make a huge difference on vision. It can help lower the risk of children and young adults developing myopia, or nearsightedness as it’s commonly known.	https://www.rebuildyourvision.com/blog/vision-conditions/nearsightedness/natural-light-essential-normal-eye-development	16
4	An examination of four studies that together included more than 8,600 people found that eating more saturated fat led to a 39% higher risk for Alzheimer's and more than double the risk for dementia in general. For each additional 4 grams per day of saturated fat people consumed, the risk for dementia increased by 15%.	https://www.health.harvard.edu/healthbeat/brain-draining-foods	16
5	Red meat, butter, cream, whole milk. All of these animal-based foods are high in saturated fat, which raises blood levels of unhealthy LDL cholesterol. When cholesterol builds up in arteries, it sets off a chain of events that can ultimately lead to a stroke.	https://www.health.harvard.edu/healthbeat/brain-draining-foods	16
292	Both unprocessed and processed red meat are linked to higher risks of cardiovascular disease and diabetes, with no apparent difference in risk between men and women.	https://www.health.harvard.edu/staying-healthy/men-women-and-red-meat-risk-maybe-both-sexes-should-put-down-the-burger	16
158	Limited ankle mobility manifests itself as a functional limitation in everyday tasks such as walking, negotiating stairs, and even in athletic endeavors such as achieving proper squat depth or cutting.	https://theprehabguys.com/unlock-ankle-mobility/	64
100	If you struggle to maintain good form during an exercise, drop back to an easier variation of the exercise to build those stabilizing muscles necessary for good form.	\N	32
87	Muscle length and strength between opposing muscle groups need to be in balance for normal movement and function.	https://www.healthline.com/health/muscle-imbalance	32
71	By sitting all day, you’re not depending on your powerful lower body muscles to hold you up. This leads to muscle atrophy, which is the weakening of these muscles. Without strong leg and glute muscles to stabilize you, your body is at risk of injury.	https://www.healthline.com/health/workplace-health/things-that-happen-when-you-sit-down-all-day	32
105	The last few difficult repetitions, when the speed of movement slows down due to fatigue, are important for creating adaptation.	https://human-movement.com/why-reps-and-sets-for-injury-rehab-are-not-important/	32
172	Working at the right tempo helps you stay in control rather than compromise strength gains through momentum. For example, count to three while lowering a weight, hold, then count to three while raising it to the starting position.	https://www.health.harvard.edu/exercise-and-fitness/7-tips-for-a-safe-and-successful-strength-training-program	32
173	Focus on form, not weight. Align your body correctly and move smoothly through each exercise. Poor form can prompt injuries and slow gains.	https://www.health.harvard.edu/exercise-and-fitness/7-tips-for-a-safe-and-successful-strength-training-program	32
83	Hold onto pullup bars or fitness rings using your fingers. This will help build better grip strength and will help prevent calluses from your palm slipping down the bar.	https://stronglifts.com/pullups/	32
176	My best is always good enough.	\N	4096
355	My cooking goals are attainable.	\N	4096
179	My curiosity is stronger than my fear.	\N	4096
182	I am unaffected by the judgement of others.	\N	4096
186	Each day I do the best I can.	\N	4096
188	I embrace both my good and bad qualities.	\N	4096
193	I am not defined by laziness, self-doubt, or numbers.	\N	4096
306	I am worthy and deserve respect.	\N	4096
170	Pay attention to your breathing during your workouts. Exhale as you work against resistance by lifting, pushing, or pulling; inhale as you release.	https://www.health.harvard.edu/exercise-and-fitness/7-tips-for-a-safe-and-successful-strength-training-program	32
189	I accept who I am.	\N	4096
31	Let go of greed, aversion, and delusion.	\N	4
307	I will not be put down by people or external circumstances.	\N	4096
309	I believe in myself.	\N	4096
313	I am confident and strong.	\N	4096
167	Keep challenging muscles by slowly increasing weight or resistance. The right weight for you differs depending on the exercise. Choose a weight that tires the targeted muscle or muscles by the last two repetitions while still allowing you to maintain good form. If you can't do the last two reps, choose a lighter weight. When it feels too easy to complete add weight (roughly 1 to 2 pounds for arms, 2 to 5 pounds for legs), or add another set of repetitions to your workout (up to three sets). If you add weight, remember that you should be able to do all the repetitions with good form and the targeted muscles should feel tired by the last two.	https://www.health.harvard.edu/exercise-and-fitness/7-tips-for-a-safe-and-successful-strength-training-program	32
64	You are beautiful!	\N	2
78	:)	\N	2
55	Close your eyes and take a few deep breaths.	\N	4
126	Strength is key for a healthy body. Mobility and flexibility allow us to feel supple and move with less restriction.	https://www.health.harvard.edu/topics/mobility	64
143	Tendons lag behind muscles by 2-5 years in their strength adaptation – depending on how one uses them. Don’t push harder or increase your loads at a rate faster than what your tendons can adapt to.	Dr. Nikita A. Vizniak	32
141	Self-monitoring diet and weight increases self-awareness, and this has been shown to positively influence eating and exercise behaviors.	https://journals.lww.com/acsm-healthfitness/Fulltext/2006/01000/Self_Monitoring__Influencing_Effective_Behavior.7.aspx	8
147	When you think about your body as a garden, it’s almost ludicrous to even consider the idea of forcing some type of adaptation. All you can do is nurture it and provide it with the best conditions for growth. You fertilize it, tend the soil, uproot the weeds, water it, leave it in the sunlight, and give it the best conditions for growth. It will only grow as well as its circumstances allow. That’s a much more accurate metaphor for how training works.	Greg Nuckols	8
6	Eating too many foods made with refined flour can affect your blood pressure and diabetes risk over time. Look for foods labeled "100% whole grain" to maximize the fiber and nutrient content of the grain products you buy.	https://www.health.harvard.edu/healthbeat/brain-draining-foods	1024
145	Large volumes of predominantly plyometric training, such as sports, may lead to imbalances in muscle and tendon properties and eventually result in injury. An imbalance in muscle and tendon properties can be prevented by regularly performing heavy resistance training.	https://www.basvanhooren.com/imbalances-in-muscle-and-tendon-strength-and-the-relation-with-injuries-and-performance/	32
171	When learning a strength training routine, many experts suggest starting with no weight, or very light weight. Concentrate on slow, smooth lifts and equally controlled descents while isolating a muscle group.	https://www.health.harvard.edu/exercise-and-fitness/7-tips-for-a-safe-and-successful-strength-training-program	32
122	Think of exercise as medicine – you need to follow the prescription to reap the benefits. Don't neglect exercise, but don't go overboard either. Moderation is key.	\N	32
123	Isometric strength training develops strength that is extremely specific to the range of motion trained. This can be helpful in training weak points. For example, isometric holds in the bottom of a squat (pause squats), or isometric deadlift holds just above or below your sticking point can help bust plateaus.	https://thebarbellphysio.com/ultimate-guide-hamstring-strain-rehabilitation/	32
132	Hard training imposes a large stress on the body and the fatigue you accumulate can mask your gains. A period of reduced training (or tapering) can help you recover, reduce your stress, and reveal the strength you gained during your hard training cycle.	https://www.health.harvard.edu/exercise-and-fitness/why-am-i-so-tired-after-exercising	32
23	Get more juice out of a lime or lemon by rolling it around on the counter until soft and slicing around the core. 	\N	1024
329	Spending just 5 minutes writing tomorrow’s to-do list before bed can help you fall asleep up to 15 minutes faster.	https://pmc.ncbi.nlm.nih.gov/articles/PMC5758411/	8
9	Food experts recommend rinsing dry rice before cooking it because it helps wash away contaminants, heavy metals, dirt and bugs that may be in the rice.	\N	1024
166	It's important to know your limits and not exceed them when exercising or participating in physical activities. Proper care of your joints can preserve function in the long term and encourage physical activity.	https://www.stanfordchildrens.org/en/topic/default?id=avoiding-joint-injuries-1-2842	8
323	The normal pH of the stomach (1.5–3.0) is highly acidic, allowing for the breakdown of proteins, fats, and other nutrients. It also acts as a defense system, killing harmful bacteria like E. coli and Klebsiella before they can colonize the small intestine. When stomach acid is low (hypochlorhydria), digestion slows, nutrient absorption decreases, and harmful microbes can flourish, leading to conditions like small intestinal bacterial overgrowth (SIBO).	Dr. William Davis	16
324	Although rarely diagnosed, hypochlorhydria affects an estimated 5–10% of the population and increases with age. It is even more common in those with digestive issues like bloating, heartburn, or slowed digestion. Causes include autoimmune gastritis (often linked to Hashimoto’s thyroiditis), H. pylori infection, and long-term use of acid-suppressing drugs like proton pump inhibitors (PPIs).	Dr. William Davis	16
325	Drugs like Prilosec and Protonix are frequently prescribed for presumed excess stomach acid, artificially creating the same effects as atrophic gastritis. This can lead to nutrient deficiencies, bacterial overgrowth, and long-term digestive dysfunction. Low stomach acid is also linked to vitamin B12 and iron deficiencies, which can cause anemia and require alternative supplementation methods like sublingual or injectable forms.	Dr. William Davis	16
294	Studies show that spending time outdoors can decrease a child's risk of developing myopia.	https://www.health.harvard.edu/blog/curbing-nearsightedness-in-children-can-outdoor-time-help-202212152868	16
317	Berries. From strawberries and blackberries to cranberries and blue­berries, these gemlike fruits are particularly potent in antioxidant and anti-inflammatory activity. Along with fiber and vitamin C, berries possess plant pigment phytochemicals, such as anthocyanins and ellagic acid, which may be behind their health benefits. Studies have linked increased berry consumption with lower risks of heart disease, Alzheimer's disease, and diabetes.	Harvard Medical School	16
318	Apples. Maybe it's true what they say about an apple a day. A study of nearly 35,000 women, found that consumption of this fruit—along with its relative, pears—was linked with a lower risk of death from heart disease. The star components of apples—fiber, vitamin C, pectin, and polyphenols—have been associated, primarily in animal studies, with anti-inflammatory effects and an increase in beneficial microbes in the gut.	Harvard Medical School	16
290	Waking up earlier is healthier than going to bed later when trying to limit the damage of sleep deprivation.	https://www.sciencedirect.com/science/article/abs/pii/S0195666323024583	16
326	Once stomach acid-producing cells are lost, they do not regenerate. However, certain strategies can help improve digestion. Betaine HCL (500–2000 mg at meals) is the most effective, while vinegar (like apple cider vinegar) can also help. B. subtilis probiotic drinks, particularly when fermented properly, may play a crucial role in managing the microbial imbalances caused by low stomach acid. While these approaches may not prevent stomach atrophy or cancer, they can support digestion and gut health.	Dr. William Davis	16
328	Emerging evidence shows that nearly 25% of non-antibiotic medications alter the gut microbiota, disrupting microbial diversity and ecosystem functions for weeks to months, or longer. Such changes can affect systemic immunity, inflammation, glucose metabolism, and overall homeostasis, particularly with chronic polypharmacy.	Jeannie Gorman, MS, CCN	16
50	Grapes. These succulent fruits are burst­ing with fiber, vitamins C and K, and powerful phytochemicals.	Harvard Medical School	16
316	I can do this.	\N	4096
43	Reward yourself after achieving special cooking related milestones. Nothing motivates like success!	\N	2048
356	As you age, balance becomes even more essential, and you should approach it like any other part of your fitness. Strong balancing skills not only can protect you from falling, but they can also reduce the likelihood of a severe injury if you do.	Kaitlyn Buckwell	32
357	When researchers pooled findings from 38 randomized controlled trials, they found that magnesium supplements may modestly lower blood pressure, especially in two groups: people with high blood pressure and those with low magnesium levels.	https://www.health.harvard.edu/nutrition/should-you-take-a-magnesium-supplement-to-lower-your-blood-pressure	16
358	Abundant research shows it's important to eat enough protein, but there are many ways to get that protein, and some are more healthful than others. People who limit how much meat they eat tend to have lower risks for chronic diseases. Plant protein sources (beans, lentils, soy foods, nuts, seeds) and seafood offer the most health benefits. Getting enough protein, along with physical activity, is important for staying strong, healthy, and independent.	Harvard Medical School	1024
359	The U.S. government's Dietary Guidelines for Americans recommend limiting saturated fat intake to less than 10% of daily calories. The same goes for added sugars (sugars added during processing). If you have a 2,000-calorie-a-day diet, that means that no more than 200 calories a day should come from added sugars. As for sodium, keep it below 2,300 milligrams (mg) per day. The average American consumes more than 3,400 mg per day.	Harvard Medical School	1024
360	A 2019 National Institutes of Health study definitively showed that eating a diet high in ultra-processed foods causes weight gain and unhealthy shifts in blood sugar and blood cholesterol. For the healthiest diet, rely as much as possible on whole foods (that is, unprocessed foods, such as broccoli, apples, and almonds) and minimally processed foods (such as plain yogurt, canned tuna, and natural peanut butter). Processing tends to strip away nutrients while adding extra fats, sugars, and sodium, not to mention other additives and preservatives.	Harvard Medical School	1024
361	To meet nutrient needs, it's important to choose a variety of nutrient-dense foods across and within all food groups. Choosing nutrient-dense foods helps you get the nutrients you need without taking in too many calories.	Harvard Medical School	1024
169	Give muscles time off. Strength training causes tiny tears in muscle tissue. These tears aren't harmful, but they are important: muscles grow stronger as the tears knit up. Always give your muscles at least 48 hours to recover before your next strength training session.	https://www.health.harvard.edu/exercise-and-fitness/7-tips-for-a-safe-and-successful-strength-training-program	32
168	Stick with your routine — working all the major muscles of your body two or three times a week is ideal.	https://www.health.harvard.edu/exercise-and-fitness/7-tips-for-a-safe-and-successful-strength-training-program	32
131	A full night's sleep gives your body time to recover, conserve energy, and repair and build up the muscles worked during exercise.	https://www.acefitness.org/resources/everyone/blog/7818/7-benefits-of-sleep-for-exercise-recovery/	32
130	You tear muscle fibers in the gym and repair/grow stronger muscle while you rest. Recovery time is incredibly crucial to a fitness regimen.	https://www.healthline.com/health/muscle-recovery	32
41	It is tempting to avoid the motions that cause you discomfort. But limiting your movements can weaken muscles and make compound joint trouble worse.	https://www.health.harvard.edu/pain/exercise-an-effective-prescription-for-joint-pain	32
125	Injured muscle tissue responds much better to gentle exercise and movement than it does vigorous stretching.	https://www.physio-network.com/blog/stretch-muscle-strain/	32
95	Protein is an important macronutrient essential for muscle protein synthesis (MPS), muscle growth and function.	https://www.verywellfit.com/muscle-protein-synthesis-and-muscle-growth-4148337	32
93	For the best strength gain, lift weights at around 60-80% of your 1 rep max (the most weight you can safely lift for 1 rep in good form). Perform reps until muscle failure or until you can no longer maintain good form.	https://www.healthline.com/health/fitness/how-to-build-strength-guide	32
142	Muscle and tendon injuries tend to occur when the muscle is overloaded, especially in a lengthened position. Eccentric exercises load the muscle while it is getting longer. This type of training has been shown to help prevent injuries.	https://foreverfitscience.com/workout-programs/eccentric-exercises/	64
362	Plant foods — vegetables, fruits, legumes, whole grains, nuts, and seeds — offer a wealth of vitamins and minerals, as well as fiber and healthful compounds called phytochemicals (literally "plant chemicals," natural substances in plants that offer humans a range of health benefits, including antioxidant, anti-inflammatory, and even anticancer activity). At the same time that many plant foods are high in nutrients, they are relatively low in calories. The combination of high nutrient content and low calories — a quality known as nutrient density — means that a plant-heavy diet can be good for both health and weight loss. Because people often underestimate how large their portions of fruits and vegetables should be, Harvard nutritionists devised the Harvard Healthy Eating Plate to provide a graphic representation of a healthy dinner. Fully half the plate contains produce.	Harvard Medical School	1024
90	The Shavasana pose is a great way to relax and relieve tension in the body after a workout.	\N	32
18	Choose clothes and shoes designed for your type of exercise. Replace shoes or insoles as the cushioning wears out.	https://www.health.harvard.edu/healthbeat/10-tips-for-exercising-safely	32
195	Research teams from Harvard and elsewhere found that people who practiced yoga improved two markers of frailty — walking speed and the ability to get up from a chair — compared with people who didn't practice yoga.	https://www.health.harvard.edu/staying-healthy/harvard-led-study-yoga-fights-frailty	8
192	Practicing everyday mindfulness can also improve your memory and concentration skills and help you feel less distracted and better able to manage crises.	https://www.health.harvard.edu/blog/evoking-calm-practicing-mindfulness-in-daily-life-helps-202110142617	4
162	Keep in shape. A high cardiovascular fitness level is crucial to avoid joint injuries. Otherwise, as you tire your form can fail and your joints carry unbalanced weight.	https://www.stanfordchildrens.org/en/topic/default?id=avoiding-joint-injuries-1-2842	8
24	Chew your food at least 20-30 times before swallowing.	\N	8
161	Never skip your warm-up or cool down. Tight or stiff muscles around a joint will make the area more prone to injury. This is especially important in sports that require quick movements, such as basketball and tennis.	https://www.stanfordchildrens.org/en/topic/default?id=avoiding-joint-injuries-1-2842	32
160	Train smart by cross-training. Repetitive-motion injuries caused by doing just one sport or workout are some of the most common. You can prevent them by doing different sports or activities that work different muscles. For example, if you mostly ride a bike, take a core-strengthening class once a week.	https://www.stanfordchildrens.org/en/topic/default?id=avoiding-joint-injuries-1-2842	32
159	Avoid doing too much, too soon. Never increase the length of your workouts by more than 10 percent from one week to the next, and never increase both the length and intensity of your workout at the same time.	https://www.stanfordchildrens.org/en/topic/default?id=avoiding-joint-injuries-1-2842	32
150	Back muscles and your core help to stabilize your body. If your core is weak, the other surrounding muscles have to compensate. Over time, these muscles can suffer strain, which leads to lingering pain.	https://www.health.harvard.edu/blog/straight-talk-on-planking-2019111318304	32
149	Look straight ahead at a distant object when you do unstable exercises. If you look at the floor when you do exercises that challenge your balance and stability, it'll shift your weight forward, putting stress on your lower back.	https://www.menshealth.com/fitness/a19548559/best-loaded-carries/	32
152	Varying exercise selection has a positive effect on enhancing motivation to train, while eliciting similar improvements in muscular adaptations.	https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6934277/	32
156	For plyometric training to be effective, it needs to provide a high neural stimulus with no to very little fatigue.	https://christianbosse.com/how-many-reps-for-plyometrics/	32
293	The most powerful way to protect the brain is to live a healthy lifestyle. The healthy habits to include are summed up with the acronym SHIELD: Sleep at least seven hours a night, Handle stress, Interact with friends, Exercise daily, Learn new things, and eat a healthy Diet.	https://www.health.harvard.edu/mind-and-mood/shield-your-brain-from-decline	8
155	If an exercise causes pain, the solution is simple. Stop doing it, and find a similar one that doesn't. There is no single 'must do' exercise that can't be replaced with something else.	Christian Finn	32
\.


--
-- Name: footnote_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."footnote_Id_seq"', 362, true);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: footnote PK_footnote; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.footnote
    ADD CONSTRAINT "PK_footnote" PRIMARY KEY ("Id");


--
-- PostgreSQL database dump complete
--

\unrestrict 2OcdjgdsopxDpyhBFKycmDneCHfBATRVMTui4Mc7H0MXTHfPeb0UxhgLQkYShOH

